# train a miniature character-level shakespeare model
# good for debugging and playing on macbooks and such

out_dir: 'out-shakespeare-char'
eval_interval: 250 # keep frequent because we'll overfit
eval_iters: 200
log_interval: 10 # don't print too too often
eval_only: false
# we expect to overfit on this small dataset, so only save when val improves
always_save_checkpoint: false

wandb_log: false # override via command line if you like
wandb_project: 'shakespeare-char'
wandb_run_name: 'mini-gpt'

dataset: 'shakespeare_char'
gradient_accumulation_steps: 1
batch_size: 64
block_size: 256 # context of up to 256 previous characters

# baby GPT model :)
n_layer: 6
n_head: 6
n_embd: 384
dropout: 0.2
bias: false

# adamw optimizer
learning_rate: 1.0e-3 # with baby networks can afford to go a bit higher
max_iters: 5000
weight_decay: 1.0e-1
beta1: 0.9
beta2: 0.99 # make a bit bigger because number of tokens per iter is small
grad_clip: 1.0

# learning rate decay settings
decay_lr: true
warmup_iters: 100 # not super necessary potentially
lr_decay_iters: 5000 # make equal to max_iters usually
min_lr: 1.0e-4 # learning_rate / 10 usually

# DDP settings
backend: 'nccl'

# system
device: 'cuda' # override with 'mps' for Apple Silicon or 'cpu' for Intel Macs
dtype: 'bfloat16' # 'float32' for MPS/CPU
compile: true # set to false for MPS/CPU
init_from: 'scratch'

